#!/bin/bash
set -eu

SCRIPT_DIR=$(cd -- "$(dirname -- ${BASH_SOURCE[0]})" &>/dev/null && pwd)
APP_NAME="$(basename $SCRIPT_DIR)"

BASH_PROFILE="$HOME/.profile"
if [ -f "$HOME/.bash_profile" ]; then
	BASH_PROFILE="$HOME/.bash_profile"
fi

USER_PROFILE="$HOME/.$USER.profile"
USER_PROFILE_STR=$(printf '"$HOME/.%s.profile"' "$USER")

begin_custom_block() {
	f="$1"
        printf "\n# BEGIN $APP_NAME\n" >>"$f"
}

end_custom_block() {
	f="$1"
        printf "# END $APP_NAME\n" >> "$f"
}

write_generated_header() {
	f="$1"
	cat <<-EOS >"$f"
		# Generated by $APP_NAME
		# Do not edit; edit template instead:
		# $SCRIPT_DIR/profile
		#
	EOS
}

set_user_profile() {
	begin_custom_block "$BASH_PROFILE"
	printf "source $USER_PROFILE_STR\n" >>"$BASH_PROFILE"
	end_custom_block "$BASH_PROFILE"

	write_generated_header "$USER_PROFILE"
	cat "$SCRIPT_DIR/profile" >> "$USER_PROFILE"

}

copy_conf_files() {
	for i in "$SCRIPT_DIR"/conf/{.*,*}; do
		if [[ -r "$i" ]]; then
			cp "$i" "$HOME/"
		fi
	done
}

set_user_profile
copy_conf_files
